version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    restart: unless-stopped
    container_name: traefik
    labels:
      traefik.frontend.rule: "Host:monitor.localhost"
      traefik.port: 8080
      traefik.enable: true
      traefik.docker.network: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./conf/traefik.toml:/traefik.toml
      - ./conf/acme.json:/acme.json
#      - ./conf/certs/:/certs/
    networks:
     - proxy
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.frontend.rule: "Host:dozzle.localhost"
      traefik.port: 8080
      traefik.docker.network: proxy
      traefik.enable: true
    environment:
      DOZZLE_LEVEL: trace
      DOZZLE_USERNAME: dozzle
      DOZZLE_PASSWORD: dozzle
    networks:
     - proxy

networks:
  proxy:
    external: true

