services:
  traefik:
    image: traefik:2.9
    restart: unless-stopped
    container_name: traefik-owo-${APP_ENV:-dev}
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/traefik.${APP_ENV:-dev}.yml:/traefik.yml:ro"
      - "./conf/traefik_dyn.yml:/traefik_dyn.yml:ro"
      - "./conf/.htpasswd:/.htpasswd:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`$HOST_DOMAIN`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth@file"
networks:
  default:
    name: traefik-proxy
    external: true
