defaultEntryPoints = ["http"]#, "https"
logLevel = "INFO"

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$9yxowblk$n1QOUZb4EtEye8wijJkok0"]
  [entryPoints.http]
    address = ":80"
#      [entryPoints.http.redirect]
#        entryPoint = "https"
#  [entryPoints.https]
#    address = ":443"
#      [entryPoints.https.tls]
#        [[entryPoints.https.tls.certificates]]
#          certFile = "/path_to.crt"
#          keyFile = "/path_to.key"

[api]
entrypoint="dashboard"

#[acme]
#email = "mail@domain"
#storage = "acme.json"
#entryPoint = "https"
#onHostRule = true
#  [acme.httpChallenge]
#  entryPoint = "http"

[docker]
domain = "localhost"
watch = true
network = "proxy"
exposedByDefault = false
#swarmMode = true

[traefikLog]
  filePath = "/var/log/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/var/log/traefik_access.log"
  format   = "json"