## STATIC CONFIGURATION
log:
  level: INFO

api:
  #insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certResolver: letsEncryptResolver

certificatesResolvers:
  letsEncryptResolver:
    acme:
      ## TODO: Set your e-mail here
      email: "username@emailserver.com"
      storage: "/letsencrypt/acme.json"
      tlschallenge: true
      # Uncomment when testing
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: traefik-proxy
  file:
    filename: /traefik_dyn.yml
    watch: true
