## STATIC CONFIGURATION
log:
  level: INFO

api:
  #insecure: true
  dashboard: true

entryPoints:
  http:
    address: ":80"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: traefik-proxy
  file:
    filename: /traefik_dyn.yml
    watch: true